---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app: otel-collector
spec:
  ports:
    - name: "55690"
      port: 55690
      targetPort: 55690
    - name: "55689"
      port: 55689
      targetPort: 55689
    - name: "55679"
      port: 55679
      targetPort: 55679
    - name: "13133"
      port: 13133
      targetPort: 13133
  type: LoadBalancer
  loadBalancerIP: 192.168.0.207
  selector:
    app: otel-collector
status:
  loadBalancer: {}
