---
apiVersion: v1
kind: Service
metadata:
  name: skywalkingui
  labels:
    app: skywalkingui
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: skywalkingui
status:
  loadBalancer: {}
