---
apiVersion: v1
kind: Service
metadata:
  name: skywalking
  namespace: observability
  labels:
    app: skywalking
spec:
  ports:
    - name: "11800"
      port: 11800
      targetPort: 11800
    - name: "12800"
      port: 12800
      targetPort: 12800
  type: LoadBalancer
  loadBalancerIP: 192.168.100.208
  selector:
    app: skywalking
status:
  loadBalancer: {}
