---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-deployment
  labels:
    app: skywalking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking
  template:
    metadata:
      labels:
        app: skywalking
    spec:
      containers:
        - name: skywalking
          env:
            # - name: "SW_STORAGE"
            #   value: "elasticsearch"
            # - name: "SW_STORAGE_ES_CLUSTER_NODES"
            #   value: "opensearch:9200"
            # - name: "SW_STORAGE_ES_HTTP_PROTOCOL"
            #   value: "https"
            # - name: "SW_OTEL_RECEIVER"
            #   value: "default"
            # - name: "SW_ES_USER"
            #   value: "admin"
            # - name: "SW_ES_PASSWORD"
            #   value: "admin"
            # - name: "SW_STORAGE_ES_SSL_JKS_PATH"
            #   value: "/usr/share/certs/KeyStore.jks"
            # - name: "SW_STORAGE_ES_SSL_JKS_PASS"
            #   value: "changeit"
            - name: "SW_STORAGE"
              value: "postgresql"
            - name: "SW_JDBC_URL:"
              value: "jdbc:postgresql://postgres:5432/skywalking"
            - name: "SW_DATA_SOURCE_USER"
              value: "skywalking"
            - name: "SW_DATA_SOURCE_PASSWORD"
              value: "skywalking"
            - name: "SW_DATA_SOURCE_CACHE_PREP_STMTS"
              value: "true"
            - name: "SW_DATA_SOURCE_PREP_STMT_CACHE_SQL_SIZE"
              value: "250"
            - name: "SW_OTEL_RECEIVER"
              value: "default"
          image: apache/skywalking-oap-server:9.7.0
          ports:
            - containerPort: 11800
            - containerPort: 12800
            # - containerPort: 9440
          resources:
            limits:
              memory: 1G
            requests:
              memory: 1G
          # livenessProbe:
          #   httpGet:
          #     path: /ping
          #     port: 8123
          #   failureThreshold: 1
          #   periodSeconds: 30
          #   # Override pod-level terminationGracePeriodSeconds #
          #   # terminationGracePeriodSeconds: 60
          # startupProbe:
          #   httpGet:
          #     path: /ping
          #     port: 8123
          #   initialDelaySeconds: 15
          #   periodSeconds: 30
          volumeMounts:
          - name: truststore
            mountPath: /usr/share/certs
      volumes:
        - name: truststore
          configMap:
            name: skywalking-config-files
            items:
            - key: KeyStore.jks
              path: KeyStore.jks
      restartPolicy: Always
