---
apiVersion: v1
kind: Service
metadata:
  name: skywalking
  labels:
    app: skywalking
spec:
  ports:
    - name: "11800"
      port: 11800
      targetPort: 11800
    - name: "12800"
      port: 12800
      targetPort: 9600
  type: LoadBalancer
  selector:
    app: skywalking
status:
  loadBalancer: {}
