---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-timeseries-pv-claim
  namespace: databases
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
