---
tasks:
  - name: Setup base tools
    become: yes
    package:
      name:
        - vim
        - curl
        - wget
        - git
        - mc
      state: present

  - name: Validate cgroup memory is present
    lineinfile: 
      path: /boot/cmdline.txt
      regexp: "^(.*) cgroup_memory=1 cgroup_enable=memory"
      state: absent
    check_mode: yes
    register: cgroup_memory_presence

  - name: Setup /boot/cmdline.txt
    become: yes
    ansible.builtin.lineinfile:
      path: /boot/cmdline.txt
      backrefs: yes
      regexp: "^(.*)$"
      line: "\\1 cgroup_memory=1 cgroup_enable=memory"
      state: present
    when: not cgroup_memory_presence.changed
    register: cmdline_block

  - name: Display cmdline.txt contents
    command: cat cmdline.txt chdir=/boot
    register: command_output

  - name: Print to console
    debug:
      msg: "{{command_output.stdout}}"

  - name: Reboot host and wait for it to restart
    become: yes
    reboot:
      msg: "Reboot initiated by Ansible"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami
    when: cmdline_block.changed
