---
- name: Setup base tools
  become: yes
  package:
    name:
      - vim
      - curl
      - wget
      - git
      - mc
    state: present

- name: Is cmdline.txt file on the new path
  stat:
    path: /boot/firmware/cmdline.txt
  register: cmdline_stat_result


- name: Set cmdline.txt file path (new path)
  set_fact:
    cmdline_path: "{{ '/boot/firmware/cmdline.txt' if cmdline_stat_result.stat.exists else '/boot/cmdline.txt' }}"

- name: Validate cgroup memory is present
  lineinfile: 
    path: "{{ cmdline_path }}"
    regexp: "^(.*) cgroup_memory=1 cgroup_enable=memory"
    state: absent
  check_mode: yes
  register: cgroup_memory_presence


- name: Setup cmdline.txt
  become: yes
  ansible.builtin.lineinfile:
    path: "{{ cmdline_path }}"
    backrefs: yes
    regexp: "^(.*)$"
    line: "\\1 cgroup_memory=1 cgroup_enable=memory"
    state: present
  when: not cgroup_memory_presence.changed
  register: cmdline_block

- name: Display cmdline.txt contents
  command: "cat {{ cmdline_path }} chdir=/boot"
  register: command_output

- name: Print to console
  debug:
    msg: "{{command_output.stdout}}"

- name: Reboot host and wait for it to restart
  become: yes
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: cmdline_block.changed
