---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  ports:
    - name: "4317"
      port: 4317
      targetPort: 4317
    - name: "13133"
      port: 13133
      targetPort: 13133
    - name: "4318"
      port: 4318
      targetPort: 4318
    - name: "55690"
      port: 55690
      targetPort: 55690
    - name: "55679"
      port: 55679
      targetPort: 55679
  type: LoadBalancer
  selector:
    app: otel-collector
status:
  loadBalancer: {}
