---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: observability
  labels:
    app: opensearch
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: "9600"
      port: 9600
      targetPort: 9600
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: 192.168.0.203
  selector:
    app: opensearch

