---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-deployment
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
            - containerPort: 9600
          resources:
            limits:
              memory: 2G
            requests:
              memory: 1.5G
          startupProbe:
            exec:
              command: ["/bin/sh", "-c", "/setup/init_indexes.sh"]
            failureThreshold: 30
            periodSeconds: 30
            initialDelaySeconds: 30
            timeoutSeconds: 20
          volumeMounts:
            - name: init-script
              mountPath: /setup
            - mountPath: "/usr/share/opensearch/data"
              name: opensearch-pv-storage
      volumes:
        - name: init-script
          configMap:
            name: opensearch-config-files
            defaultMode: 0777
            items:
              - key: init_indexes.sh
                path: init_indexes.sh
        - name: opensearch-pv-storage
          persistentVolumeClaim:
            claimName: opensearch-pv-claim
      restartPolicy: Always
