---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-deployment
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
            - name: plugins.security.ssl.transport.enforce_hostname_verification
              value: "false"
          ports:
            - containerPort: 9200
            - containerPort: 9600
          resources:
            limits:
              memory: 2G
            requests:
              memory: 1.5G
          volumeMounts:
            - mountPath: "/usr/share/opensearch/data"
              name: opensearch-pv-storage
          startupProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: Basic YWRtaW46YWRtaW4=
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: Basic YWRtaW46YWRtaW4=
            initialDelaySeconds: 30
            periodSeconds: 30

      volumes:
        - name: opensearch-pv-storage
          persistentVolumeClaim:
            claimName: opensearch-pv-claim
      restartPolicy: Always
