---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pv-claim
  namespace: observability
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
