# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: persistent-volume
#   labels:
#     type: local
# spec:
#   storageClassName: local-path
#   capacity:
#     storage: 8Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pv-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
