---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-deployment
  namespace: observability
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      namespace: observability
      labels:
        app: opensearch
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.5.0
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms756m -Xmx756m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
            - name: plugins.security.ssl.transport.pemcert_filepath
              value: /usr/share/opensearch/config/certs/node1.pem
            - name: plugins.security.ssl.transport.pemkey_filepath
              value: /usr/share/opensearch/config/certs/node1-key.pem
            - name: plugins.security.ssl.transport.pemtrustedcas_filepath
              value: /usr/share/opensearch/config/certs/root-ca.pem
            - name: plugins.security.ssl.http.pemcert_filepath
              value: /usr/share/opensearch/config/certs/node1.pem
            - name: plugins.security.ssl.http.pemkey_filepath
              value: /usr/share/opensearch/config/certs/node1-key.pem
            - name: plugins.security.ssl.http.pemtrustedcas_filepath
              value: /usr/share/opensearch/config/certs/root-ca.pem
            - name: plugins.security.ssl.transport.enforce_hostname_verification
              value: "false"
            - name: plugins.security.ssl.http.enabled
              value: "true"

          ports:
            - containerPort: 9200
            - containerPort: 9600
          resources:
            limits:
              memory: 2G
            requests:
              memory: 2G
          volumeMounts:
            - name: opensearch-pv-storage
              mountPath: "/usr/share/opensearch/data"
            - name: opensearch-certificates
              mountPath: /usr/share/opensearch/config/certs
          startupProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: Basic YWRtaW46YWRtaW4=
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
              scheme: HTTPS
              httpHeaders:
                - name: Authorization
                  value: Basic YWRtaW46YWRtaW4=
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 30

      volumes:
        - name: opensearch-pv-storage
          persistentVolumeClaim:
            claimName: opensearch-pv-claim
        - name: opensearch-certificates
          configMap:
            name: opensearch-certs
            items:
            - key: admin-key.pem
              path: admin-key.pem
            - key: admin.pem
              path: admin.pem
            - key: client-key.pem
              path: client-key.pem
            - key: client.pem
              path: client.pem
            - key: node1-key.pem
              path: node1-key.pem
            - key: node1.pem
              path: node1.pem
            - key: root-ca-key.pem
              path: root-ca-key.pem
            - key: root-ca.pem
              path: root-ca.pem
            - key: root-ca.srl
              path: root-ca.srl
      restartPolicy: Always

