---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-query-deployment
  labels:
    app: jaeger-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-query
  template:
    metadata:
      labels:
        app: jaeger-query
    spec:
      containers:
      - name: jaeger-query
        image: jaegertracing/jaeger-query:latest
        env:
          - name: SPAN_STORAGE_TYPE
            value: opensearch
          - name: ES_TAGS_AS_FIELDS_ALL
            value: "true"
          - name: ES_USERNAME
            value: admin
          - name: ES_PASSWORD
            value: admin
          - name: ES_TLS_SKIP_HOST_VERIFY
            value: "true"
          - name: ES_SERVER_URLS
            value: https://opensearch:9200
        ports:
          - containerPort: 14269
          - containerPort: 14268
          - containerPort: 14267
          - containerPort: 14250
          - containerPort: 9411
          - containerPort: 4317
        command: [ "/go/bin/query-linux" ]
        args: [ "--es.server-urls=https://opensearch:9200", "--es.tls.enabled=true", "--query.otlp.enabled=true" ]
        resources:
          limits:
            memory: 256M
          requests:
            memory: 256M
      restartPolicy: Always
