---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
spec:
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
    - name: "16686"
      port: 16686
      targetPort: 16686
    - name: "14268"
      port: 14268
      targetPort: 14268
  type: LoadBalancer
  selector:
    app: jaeger
status:
  loadBalancer: {}
