---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: observability
  labels:
    app: jaeger
spec:
  ports:
    - name: "4317"
      port: 4317
      targetPort: 4317
    - name: "16686"
      port: 16686
      targetPort: 16686
    - name: "8888"
      port: 8888
      targetPort: 8888
  type: LoadBalancer
  selector:
    app: jaeger
status:
  loadBalancer: {}
