---
receivers:
  otlp/traces:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55689
  otlp/metrics:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690

extensions:
  pprof:
  zpages:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health/status"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp/traces]
      processors: [batch]
      exporters: [otlp/data-prepper/traces, debug]
    metrics:
      receivers: [otlp/metrics]
      processors: [batch]
      exporters: [otlp/data-prepper/metrics, debug]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [zipkin]
  telemetry:
    logs:
      level: "debug"
exporters:
  debug:
  ## Data sources: traces
  # zipkin:
  #   endpoint: http://skywalking:9412/api/v2/spans
  # otlp/skywalking:
  #   endpoint: skywalking:11800
  #   tls:
  #     insecure: "true"
  otlp/data-prepper/traces:
    endpoint: http://data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true
  otlp/data-prepper/metrics:
    endpoint: http://data-prepper:21891
    tls:
      insecure: true
      insecure_skip_verify: true
processors:
    batch:
    span:
