---
filebeat.autodiscover:
  providers:
    - type: docker
      # exclude_lines: [ "^filebeat", "^postgres", "^data-prepper", "^opensearch", "^opensearch", "^logstash" ]
      templates:
        - config:
          - type: container
            # exclude_lines: [ "^docker.elastic.co/beats/filebeat", "^postgres", "^opensearchproject/data-prepper", "^opensearchproject/opensearch", "^opensearchproject/opensearch-dashboards", "^opensearchproject/logstash-oss-with-opensearch-output-plugin" ]
            paths:
              - /var/lib/docker/containers/${data.docker.container.id}/*.log
          condition:
            contains:
              docker.container.image.name: eldius/service-
processors:
  - add_cloud_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      max_depth: 1
      target: "parsed"
      overwrite_keys: false
      add_error_key: true


# output:
#   http:
#     hosts: ["data-prepper:2021/log/ingest"]


output.logstash:
 hosts: ["logstash:5044"]

# output.console:
#   pretty: true


#logging.selectors: [ output ]

#logging:
  # level: debug
  # level: info
  # to_files: true
  # files:
  #   path: /var/log/filebeat
  #   name: filebeat.log
  #   keepfiles: 7
  #   permissions: 0640

