entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
      port: 21890
  # buffer:
  #   bounded_blocking:
  #     buffer_size: 10240
  #     batch_size: 160
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  # buffer:
  #   bounded_blocking:
  #     buffer_size: 10240
  #     batch_size: 160
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        # cert: "/usr/share/data-prepper/root-ca.pem"
        insecure: true
        username: admin
        password: admin
        index_type: trace-analytics-raw
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  # buffer:
  #   bounded_blocking:
  #     buffer_size: 10240
  #     batch_size: 160
  processor:
    - service_map_stateful:
  sink:
    - stdout:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        # cert: "/usr/share/data-prepper/root-ca.pem"
        insecure: true
        username: admin
        password: admin
        index_type: trace-analytics-service-map

metrics-pipeline:
  source:
    otel_metrics_source:
      ssl: false
      port: 21891
  processor:
    - otel_metrics_raw_processor:
  sink:
    - stdout:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        # cert: "/usr/share/data-prepper/root-ca.pem"
        insecure: true
        username: admin
        password: admin
        index: "metrics-otel-v1"
        # index: "metrics-otel-v1-%{yyyy.MM.dd}"
        # indexAlias: "metrics-otel-v1"
        # index_type: metrics-analytics-raw

log-pipeline:
  source:
    http:
      ssl: false
      port: 2021
      health_check_service: true
      unauthenticated_health_check: true
      path: /log/ingest
      authentication:
        unauthenticated:
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        insecure: true
        username: admin
        password: admin
        index: "custom-application-logs"
        # index: "custom-logs-%{yyyy.MM.dd}"
        # indexAlias: "custom-logs"
