entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
      port: 21890
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        insecure: true
        username: admin
        password: admin
        index_type: trace-analytics-raw
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - stdout:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        insecure: true
        username: admin
        password: admin
        index_type: trace-analytics-service-map

metrics-pipeline:
  source:
    otel_metrics_source:
      ssl: false
      port: 21891
  processor:
    - otel_metrics_raw_processor:
  sink:
    - stdout:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        insecure: true
        username: admin
        password: admin
        index: "metrics-otel-v1"

log-pipeline:
  source:
    http:
      ssl: false
      port: 2021
      health_check_service: true
      unauthenticated_health_check: true
      path: /log/ingest
      authentication:
        unauthenticated:
  sink:
    - opensearch:
        hosts: [ "https://opensearch:9200" ]
        insecure: true
        username: admin
        password: admin
        index: "application-logs"
        # index: "custom-logs-%{yyyy.MM.dd}"
        # indexAlias: "custom-logs"
