---
apiVersion: v1
kind: Service
metadata:
  name: data-prepper
  labels:
    app: data-prepper
spec:
  ports:
    - name: "21890"
      port: 21890
      targetPort: 21890
    - name: "21891"
      port: 21891
      targetPort: 21891
    - name: "2021"
      port: 2021
      targetPort: 2021
  type: LoadBalancer
  selector:
    app: data-prepper
status:
  loadBalancer: {}
