---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-prepper-deployment
  labels:
    app: data-prepper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-prepper
  template:
    metadata:
      labels:
        app: data-prepper
    spec:
      containers:
        - name: data-prepper
          image: eldius/opensearch-data-prepper:2.1.1
          ports:
            - containerPort: 21890
            - containerPort: 21891
            - containerPort: 2021
          resources:
            limits:
              memory: 256M
            requests:
              memory: 256M
          volumeMounts:
          # - name: root-ca-pem
          #  mountPath: /usr/share/data-prepper/
          #  readOnly: true
          - name: data-prepper-config-yaml
            mountPath: /usr/share/data-prepper/config
            #readOnly: true
          - name: pipelines-yaml
            mountPath: /usr/share/data-prepper/pipelines
            #readOnly: true
      volumes:
        - name: root-ca-pem
          configMap:
            name: data-prepper-config-files
            items:
            - key: root-ca.pem
              path: root-ca.pem
        - name: data-prepper-config-yaml
          configMap:
            name: data-prepper-config-files
            items:
            - key: data-prepper-config.yaml
              path: data-prepper-config.yaml
            - key: log4j2-rolling.properties
              path: log4j2-rolling.properties
        - name: pipelines-yaml
          configMap:
            name: data-prepper-config-files
            items:
            - key: pipelines.yaml
              path: pipelines.yaml
      restartPolicy: Always
