---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit-deployment
  labels:
    app: fluent-bit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:latest
          ports:
            - containerPort: 24224
          resources:
            limits:
              memory: 256M
            requests:
              memory: 256M
          volumeMounts:
          - name: fluent-bit-conf
            mountPath: /fluent-bit/etc
            #readOnly: true
      volumes:
        - name: fluent-bit-conf
          configMap:
            name: fluent-bit-config-files
            items:
            - key: parsers.conf
              path: parsers.conf
            - key: fluent-bit.conf
              path: fluent-bit.conf
      restartPolicy: Always
