---
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
spec:
  ports:
    - name: "24224"
      port: 24224
      targetPort: 24224
  type: LoadBalancer
  selector:
    app: fluent-bit
status:
  loadBalancer: {}
