---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_DB
          value: root
        - name: POSTGRES_PASSWORD
          value: P@ss
        ports:
          - containerPort: 5432
        volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d/
        resources:
          limits:
            memory: 256M
          requests:
            memory: 256M
      restartPolicy: Always
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
            items:
            - key: 001_creating_app_db.sql
              path: 001_creating_app_db.sql
            - key: 002_creating_skywalking_db.sql
              path: 002_creating_skywalking_db.sql
